In [3]:
import pandas as pd
import matplotlib.pyplot as plt

In [25]:
data=pd.read_csv('top.csv',usecols=['release_year_top','popularity_top','genres_top'])
data.head()

   release_year_top  popularity_top                         genres_top
0              1960        2.610362              Drama|Horror|Thriller
1              1960        1.872132           Action|Adventure|Western
2              1960        1.136943               Action|Drama|History
3              1961        2.631987  Adventure|Animation|Comedy|Family
4              1961        1.752027               Comedy|Drama|Romance

In [26]:
data.dropna(how='any',inplace=True)
data.isnull().sum()

release_year_top    0
popularity_top      0
genres_top          0
dtype: int64

In [27]:
df=pd.DataFrame(data)
df.head()

   release_year_top  popularity_top                         genres_top
0              1960        2.610362              Drama|Horror|Thriller
1              1960        1.872132           Action|Adventure|Western
2              1960        1.136943               Action|Drama|History
3              1961        2.631987  Adventure|Animation|Comedy|Family
4              1961        1.752027               Comedy|Drama|Romance

In [28]:
newGenres=df.genres_top.str.split('|',expand=True).stack()
df.join(pd.Series(index=newGenres.index.droplevel(1),data=newGenres.values,name='modified_genres'))

,release_year_top,popularity_top,genres_top,modified_genres
0,1960,2.610362,Drama|Horror|Thriller,Drama
0,1960,2.610362,Drama|Horror|Thriller,Horror
0,1960,2.610362,Drama|Horror|Thriller,Thriller
1,1960,1.872132,Action|Adventure|Western,Action
1,1960,1.872132,Action|Adventure|Western,Adventure
1,1960,1.872132,Action|Adventure|Western,Western
2,1960,1.136943,Action|Drama|History,Action
2,1960,1.136943,Action|Drama|History,Drama
2,1960,1.136943,Action|Drama|History,History
3,1961,2.631987,Adventure|Animation|Comedy|Family,Adventure
3,1961,2.631987,Adventure|Animation|Comedy|Family,Animation
3,1961,2.631987,Adventure|Animation|Comedy|Family,Comedy
3,1961,2.631987,Adventure|Animation|Comedy|Family,Family
4,1961,1.752027,Comedy|Drama|Romance,Comedy
4,1961,1.752027,Comedy|Drama|Romance,Drama
4,1961,1.752027,Comedy|Drama|Romance,Romance
5,1961,0.900245,Music|Crime|Drama,Music
5,1961,0.900245,Music|Crime|Drama,Crime
5,1961,0.900245,Music|Crime|Drama,Drama
6,1962,3.170651,Adventure|Action|Thriller,Adventure
6,1962,3.170651,Adventure|Action|Thriller,Action
6,1962,3.170651,Adventure|Action|Thriller,Thriller
7,1962,1.168767,Adventure|Drama|History|War,Adventure
7,1962,1.168767,Adventure|Drama|History|War,Drama
7,1962,1.168767,Adventure|Drama|History|War,History
7,1962,1.168767,Adventure|Drama|History|War,War
8,1962,0.823779,Drama|Romance,Drama
8,1962,0.823779,Drama|Romance,Romance
9,1963,2.508235,Action|Thriller|Adventure,Action
9,1963,2.508235,Action|Thriller|Adventure,Thriller
...,...,...,...,...
158,2012,6.591277,Action|Crime|Drama|Thriller,Thriller
159,2013,6.112766,Animation|Adventure|Family,Animation
159,2013,6.112766,Animation|Adventure|Family,Adventure
159,2013,6.112766,Animation|Adventure|Family,Family
160,2013,5.242753,Science Fiction|Thriller|Drama,Science Fiction
160,2013,5.242753,Science Fiction|Thriller|Drama,Thriller
160,2013,5.242753,Science Fiction|Thriller|Drama,Drama
161,2013,5.111900,Action|Adventure|Fantasy,Action
161,2013,5.111900,Action|Adventure|Fantasy,Adventure
161,2013,5.111900,Action|Adventure|Fantasy,Fantasy
162,2014,24.949134,Adventure|Drama|Science Fiction,Adventure
162,2014,24.949134,Adventure|Drama|Science Fiction,Drama
162,2014,24.949134,Adventure|Drama|Science Fiction,Science Fiction
163,2014,14.311205,Action|Science Fiction|Adventure,Action
163,2014,14.311205,Action|Science Fiction|Adventure,Science Fiction
163,2014,14.311205,Action|Science Fiction|Adventure,Adventure
164,2014,12.971027,Action|Adventure|Science Fiction,Action
164,2014,12.971027,Action|Adventure|Science Fiction,Adventure
164,2014,12.971027,Action|Adventure|Science Fiction,Science Fiction
165,2015,32.985763,Action|Adventure|Science Fiction|Thriller,Action
165,2015,32.985763,Action|Adventure|Science Fiction|Thriller,Adventure
165,2015,32.985763,Action|Adventure|Science Fiction|Thriller,Science Fiction
165,2015,32.985763,Action|Adventure|Science Fiction|Thriller,Thriller
166,2015,28.419936,Action|Adventure|Science Fiction|Thriller,Action
166,2015,28.419936,Action|Adventure|Science Fiction|Thriller,Adventure
166,2015,28.419936,Action|Adventure|Science Fiction|Thriller,Science Fiction
166,2015,28.419936,Action|Adventure|Science Fiction|Thriller,Thriller
167,2015,13.112507,Adventure|Science Fiction|Thriller,Adventure
167,2015,13.112507,Adventure|Science Fiction|Thriller,Science Fiction
167,2015,13.112507,Adventure|Science Fiction|Thriller,Thriller

In [29]:
df.to_csv('splittedGenres.csv')